Fix bug in unifying records
roc-lang/roc pull request #4778
Opened 2022-12-16 03:28 UTC by joshuawarner32

This was leading us to have an infinitely-recursive type, which eventually causes layout to stack-overflow

Fixes #4739

2022-12-16 04:31 UTC, joshuawarner32 commented
Not sure why this required modifying the `glue` test? Looks to me like this potentially triggered a different bug.

2022-12-16 05:01 UTC, bhansconnect commented
Maybe `choose_merged_var` is choosing the wrong variable and we are loosing the name? I don't actually know the code you changed, but that sounds possible.

2022-12-16 05:18 UTC, joshuawarner32 commented
Interesting - can you point me to the code that's choosing R1/R2 names? Is that in glue, or somewhere deeper in the compiler?

2022-12-16 05:50 UTC, joshuawarner32 commented
Ok, I think I figured it out - I accidentally reversed some of the arguments there, which meant `choose_merged_var` choose a different default value if neither type were a `RecursiveVar`.

2022-12-16 13:51 UTC, ayazhafiz commented on crates/compiler/solve/tests/solve_expr.rs
> +    fn my_bug() {
Can this test be given a more descriptive name, e.g. "choose_correct_recursion_var_under_record"?

2022-12-16 13:53 UTC, ayazhafiz reviewed
Congratulations for resolution through the trials and tribulations of the type system!!

2022-12-16 13:53 UTC, ayazhafiz commented on crates/compiler/solve/tests/solve_expr.rs
> +    "#
```suggestion
                r#"
                Parser : [
                    Specialize Parser,
                    Record (List {parser: Parser}),
                ]
                
                printCombinatorParser : Parser -> Str
                printCombinatorParser = \parser ->
                    when parser is
                #        ^^^^^^
                        Specialize p ->
                            printed = printCombinatorParser p
                            if Bool.false then printed else "foo"
                        Record fields ->
                            fields
                                |> List.map \f ->
                                    printed = printCombinatorParser f.parser
                                    if Bool.false then printed else "foo"
                                |> List.first
                                |> Result.withDefault ("foo")
                
                printCombinatorParser (Record [])
                "#
```

to line up with how other tests of this type are indented in this file

2022-12-16 19:48 UTC, ayazhafiz requested changes
Let's also add a test to `test_mono` that ensures that this actually passes layout generation.

2022-12-17 03:46 UTC, joshuawarner32 commented
Unfortunately test_mono isn't happy ☹️ 

```
thread 'choose_correct_recursion_var_under_record' panicked at 'IR problems found:
── SYMBOL LAYOUT DOESN'T MATCH ITS USE ─────────────────────────────────────────

in main : () -> Str (no niche)

0│  procedure `#UserApp.main` ():
1│>     let `#UserApp.28` : List [<r>C List *self, C *self] = Array [];
2│      let `#UserApp.15` : [<r>C List *self, C *self] = TagId(0) `#UserApp.28`;

#UserApp.28 defined here with layout List [<r>C List *self, C *self]

1│      let `#UserApp.28` : List [<r>C List *self, C *self] = Array [];
2│>     let `#UserApp.15` : [<r>C List *self, C *self] = TagId(0) `#UserApp.28`;
3│      let `#UserApp.14` : Str = CallByName `#UserApp.printCombinatorParser` `#UserApp.15`;

#UserApp.28 used as a tag's payload here with layout List *self
── SYMBOL INITIALIZER HAS THE WRONG LAYOUT ─────────────────────────────────────

in printCombinatorParser : ([<r>C List *self, C *self]) -> Str (no niche)

8 │          ret `#UserApp.17`;
9 │>     else
10│          let `#UserApp.fields` : List [<r>C List *self, C *self] = UnionAtIndex (Id 0) (Index 0) `#UserApp.parser`;

#UserApp.fields is defined as List [<r>C List *self, C *self] but its
initializer is List *self', crates/compiler/test_mono/src/tests.rs:173:5
```

Here's the full ir:

```
procedure `#UserApp.main` ():
    let `#UserApp.28` : List [<r>C List *self, C *self] = Array [];
    let `#UserApp.15` : [<r>C List *self, C *self] = TagId(0) `#UserApp.28`;
    let `#UserApp.14` : Str = CallByName `#UserApp.printCombinatorParser` `#UserApp.15`;
    dec `#UserApp.15`;
    ret `#UserApp.14`;
procedure `#UserApp.printCombinatorParser` (`#UserApp.parser`):
    let `#UserApp.25` : U8 = 1i64;
    let `#UserApp.26` : U8 = GetTagId `#UserApp.parser`;
    let `#UserApp.27` : Int1 = lowlevel Eq `#UserApp.25` `#UserApp.26`;
    if `#UserApp.27` then
        let `#UserApp.p` : [<r>C List *self, C *self] = UnionAtIndex (Id 1) (Index 0) `#UserApp.parser`;
        let `#UserApp.printed` : Str = CallByName `#UserApp.printCombinatorParser` `#UserApp.p`;
        let `#UserApp.17` : Str = "foo";
        ret `#UserApp.17`;
    else
        let `#UserApp.fields` : List [<r>C List *self, C *self] = UnionAtIndex (Id 0) (Index 0) `#UserApp.parser`;
        let `#UserApp.22` : {} = Struct {};
        let `#UserApp.21` : List Str = CallByName `List.map` `#UserApp.fields` `#UserApp.22`;
        let `#UserApp.19` : [C {}, C Str] = CallByName `List.first` `#UserApp.21`;
        dec `#UserApp.21`;
        let `#UserApp.20` : Str = "foo";
        let `#UserApp.18` : Str = CallByName `Result.withDefault` `#UserApp.19` `#UserApp.20`;
        dec `#UserApp.20`;
        ret `#UserApp.18`;
```

2022-12-17 04:23 UTC, ayazhafiz commented
That’s okay, you can mark the proc macro as #[test_mono(no_check)]. I plan to fix that false negative when i’m back from vacation
________________________________
From: Joshua Warner ***@***.***>
Sent: Friday, December 16, 2022 9:46:54 PM
To: roc-lang/roc ***@***.***>
Cc: Ayaz ***@***.***>; Comment ***@***.***>
Subject: Re: [roc-lang/roc] Fix bug in unifying records (PR #4778)


Unfortunately test_mono isn't happy ☹️

thread 'choose_correct_recursion_var_under_record' panicked at 'IR problems found:

── SYMBOL LAYOUT DOESN'T MATCH ITS USE ─────────────────────────────────────────



in main : () -> Str (no niche)



0│  procedure `#UserApp.main` ():

1│>     let `#UserApp.28` : List [<r>C List *self, C *self] = Array [];

2│      let `#UserApp.15` : [<r>C List *self, C *self] = TagId(0) `#UserApp.28`;



#UserApp.28 defined here with layout List [<r>C List *self, C *self]



1│      let `#UserApp.28` : List [<r>C List *self, C *self] = Array [];

2│>     let `#UserApp.15` : [<r>C List *self, C *self] = TagId(0) `#UserApp.28`;

3│      let `#UserApp.14` : Str = CallByName `#UserApp.printCombinatorParser` `#UserApp.15`;



#UserApp.28 used as a tag's payload here with layout List *self

── SYMBOL INITIALIZER HAS THE WRONG LAYOUT ─────────────────────────────────────



in printCombinatorParser : ([<r>C List *self, C *self]) -> Str (no niche)



8 │          ret `#UserApp.17`;

9 │>     else

10│          let `#UserApp.fields` : List [<r>C List *self, C *self] = UnionAtIndex (Id 0) (Index 0) `#UserApp.parser`;



#UserApp.fields is defined as List [<r>C List *self, C *self] but its

initializer is List *self', crates/compiler/test_mono/src/tests.rs:173:5



Here's the full ir:

procedure `#UserApp.main` ():

    let `#UserApp.28` : List [<r>C List *self, C *self] = Array [];

    let `#UserApp.15` : [<r>C List *self, C *self] = TagId(0) `#UserApp.28`;

    let `#UserApp.14` : Str = CallByName `#UserApp.printCombinatorParser` `#UserApp.15`;

    dec `#UserApp.15`;

    ret `#UserApp.14`;

procedure `#UserApp.printCombinatorParser` (`#UserApp.parser`):

    let `#UserApp.25` : U8 = 1i64;

    let `#UserApp.26` : U8 = GetTagId `#UserApp.parser`;

    let `#UserApp.27` : Int1 = lowlevel Eq `#UserApp.25` `#UserApp.26`;

    if `#UserApp.27` then

        let `#UserApp.p` : [<r>C List *self, C *self] = UnionAtIndex (Id 1) (Index 0) `#UserApp.parser`;

        let `#UserApp.printed` : Str = CallByName `#UserApp.printCombinatorParser` `#UserApp.p`;

        let `#UserApp.17` : Str = "foo";

        ret `#UserApp.17`;

    else

        let `#UserApp.fields` : List [<r>C List *self, C *self] = UnionAtIndex (Id 0) (Index 0) `#UserApp.parser`;

        let `#UserApp.22` : {} = Struct {};

        let `#UserApp.21` : List Str = CallByName `List.map` `#UserApp.fields` `#UserApp.22`;

        let `#UserApp.19` : [C {}, C Str] = CallByName `List.first` `#UserApp.21`;

        dec `#UserApp.21`;

        let `#UserApp.20` : Str = "foo";

        let `#UserApp.18` : Str = CallByName `Result.withDefault` `#UserApp.19` `#UserApp.20`;

        dec `#UserApp.20`;

        ret `#UserApp.18`;



—
Reply to this email directly, view it on GitHub<https://github.com/roc-lang/roc/pull/4778#issuecomment-1356013791>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AE6GL6VMUQYKHLGP234BY3LWNUZS5ANCNFSM6AAAAAATAOBJ5I>.
You are receiving this because you commented.Message ID: ***@***.***>

2022-12-17 04:30 UTC, ayazhafiz commented
(or, if you’re interested in another fun dive, feel free to fix that false positive too - should be a short project)
________________________________
From: Ayaz ***@***.***>
Sent: Friday, December 16, 2022 10:23:12 PM
To: roc-lang/roc ***@***.***>
Cc: Ayaz ***@***.***>; Your activity ***@***.***>
Subject: Re: [roc-lang/roc] Fix bug in unifying records (PR #4778)


That’s okay, you can mark the proc macro as #[test_mono(no_check)]. I plan to fix that false negative when i’m back from vacation
________________________________
From: Joshua Warner ***@***.***>
Sent: Friday, December 16, 2022 9:46:54 PM
To: roc-lang/roc ***@***.***>
Cc: Ayaz ***@***.***>; Comment ***@***.***>
Subject: Re: [roc-lang/roc] Fix bug in unifying records (PR #4778)


Unfortunately test_mono isn't happy ☹️

thread 'choose_correct_recursion_var_under_record' panicked at 'IR problems found:

── SYMBOL LAYOUT DOESN'T MATCH ITS USE ─────────────────────────────────────────



in main : () -> Str (no niche)



0│ procedure `#UserApp.main` ():

1│> let `#UserApp.28` : List [<r>C List *self, C *self] = Array [];

2│ let `#UserApp.15` : [<r>C List *self, C *self] = TagId(0) `#UserApp.28`;



#UserApp.28 defined here with layout List [<r>C List *self, C *self]



1│ let `#UserApp.28` : List [<r>C List *self, C *self] = Array [];

2│> let `#UserApp.15` : [<r>C List *self, C *self] = TagId(0) `#UserApp.28`;

3│ let `#UserApp.14` : Str = CallByName `#UserApp.printCombinatorParser` `#UserApp.15`;



#UserApp.28 used as a tag's payload here with layout List *self

── SYMBOL INITIALIZER HAS THE WRONG LAYOUT ─────────────────────────────────────



in printCombinatorParser : ([<r>C List *self, C *self]) -> Str (no niche)



8 │ ret `#UserApp.17`;

9 │> else

10│ let `#UserApp.fields` : List [<r>C List *self, C *self] = UnionAtIndex (Id 0) (Index 0) `#UserApp.parser`;



#UserApp.fields is defined as List [<r>C List *self, C *self] but its

initializer is List *self', crates/compiler/test_mono/src/tests.rs:173:5



Here's the full ir:

procedure `#UserApp.main` ():

let `#UserApp.28` : List [<r>C List *self, C *self] = Array [];

let `#UserApp.15` : [<r>C List *self, C *self] = TagId(0) `#UserApp.28`;

let `#UserApp.14` : Str = CallByName `#UserApp.printCombinatorParser` `#UserApp.15`;

dec `#UserApp.15`;

ret `#UserApp.14`;

procedure `#UserApp.printCombinatorParser` (`#UserApp.parser`):

let `#UserApp.25` : U8 = 1i64;

let `#UserApp.26` : U8 = GetTagId `#UserApp.parser`;

let `#UserApp.27` : Int1 = lowlevel Eq `#UserApp.25` `#UserApp.26`;

if `#UserApp.27` then

let `#UserApp.p` : [<r>C List *self, C *self] = UnionAtIndex (Id 1) (Index 0) `#UserApp.parser`;

let `#UserApp.printed` : Str = CallByName `#UserApp.printCombinatorParser` `#UserApp.p`;

let `#UserApp.17` : Str = "foo";

ret `#UserApp.17`;

else

let `#UserApp.fields` : List [<r>C List *self, C *self] = UnionAtIndex (Id 0) (Index 0) `#UserApp.parser`;

let `#UserApp.22` : {} = Struct {};

let `#UserApp.21` : List Str = CallByName `List.map` `#UserApp.fields` `#UserApp.22`;

let `#UserApp.19` : [C {}, C Str] = CallByName `List.first` `#UserApp.21`;

dec `#UserApp.21`;

let `#UserApp.20` : Str = "foo";

let `#UserApp.18` : Str = CallByName `Result.withDefault` `#UserApp.19` `#UserApp.20`;

dec `#UserApp.20`;

ret `#UserApp.18`;



—
Reply to this email directly, view it on GitHub<https://github.com/roc-lang/roc/pull/4778#issuecomment-1356013791>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AE6GL6VMUQYKHLGP234BY3LWNUZS5ANCNFSM6AAAAAATAOBJ5I>.
You are receiving this because you commented.Message ID: ***@***.***>

—
Reply to this email directly, view it on GitHub<https://github.com/roc-lang/roc/pull/4778#issuecomment-1356027175>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AE6GL6QNOUKBQYOE6WXW7ADWNU53BANCNFSM6AAAAAATAOBJ5I>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2022-12-17 22:20 UTC, ayazhafiz approved these changes

2022-12-17 22:20 UTC, merged