Add github style links to docs sections
roc-lang/roc pull request #5132
Opened 2023-03-13 18:26 UTC by itmuckel

Fixes #5106.

2023-03-13 18:27 UTC, itmuckel commented on flake.nix
> +          jq
This was required for `./www/build.sh` to work.

2023-03-13 19:14 UTC, Anton-4 requested changes
Thanks for your PR @itmuckel!
There are some small things that can be improved:
- Could the link "icon" be changed to have the same color as the type next to it? Right now it might not contrast enough with the background in dark mode for people who require a higher contrast to see well.
- Double-clicking the type and pressing Ctrl+C now also copies the link icon. Can you see if that can be avoided?
- Would it be possible to de-activate the hover after say 3 seconds instead of instantly when the mouse moves? Otherwise you have to be sort of careful with your mouse movement to make the link icon not disappear. This is not a big deal for most people but could be really annoying for those with a disability.

This is no list of tasks you must do, I'm happy to take care of it if you can't find the time.

2023-03-14 09:24 UTC, Anton-4 commented
The next few days is fine, on firefox there are [some buttons](https://discourse.mozilla.org/t/how-to-test-preferred-color-scheme-dark-mode-with-firefox/40769/5) in the developer console (Ctrl+Shift+i).

2023-03-15 18:20 UTC, itmuckel commented
@Anton-4 Okay, that should be it 🙂

2023-03-17 20:19 UTC, itmuckel commented
Sorry, I've seen that the commits weren't linked to my account and amended them with my correct email. 😅

2023-03-18 10:45 UTC, Anton-4 approved these changes

2023-03-18 10:46 UTC, Anton-4 commented
Can you merge this @rtfeldman?

2023-03-20 18:54 UTC, itmuckel commented
Rebased and signed commits. 🙂

2023-03-20 19:08 UTC, Anton-4 approved these changes
Thanks @itmuckel!

2023-03-21 14:22 UTC, merged