use explicit stack to prevent stack overflow in drop specialization
roc-lang/roc pull request #5657
Opened 2023-07-10 19:08 UTC by folkertdev

2023-07-10 19:19 UTC, folkertdev commented on crates/compiler/mono/src/drop_specialization.rs
> +            } = call;
done

2023-07-11 08:11 UTC, JTeeuwissen requested changes

2023-07-11 08:11 UTC, JTeeuwissen commented on crates/compiler/mono/src/drop_specialization.rs
> +                                // alloc_let_with_continuation!(environment)
this can be removed?

2023-07-11 08:11 UTC, JTeeuwissen commented on crates/compiler/mono/src/drop_specialization.rs
> +                match stmt {
I'd prefer a 
```rs
while let Stmt::Let(binding, expr, layout, next_stmt) = stmt
```

2023-07-11 08:11 UTC, JTeeuwissen commented on crates/compiler/mono/src/drop_specialization.rs
> +                ));
I'd prefer a fold
```rs
let final_continuation = stack.into_iter().rev().fold(
    specialize_drops_stmt(
        arena,
        layout_interner,
        ident_ids,
        environment,
        final_continuation,
    ),
    |final_continuation, (binding, expr, layout)| {
        arena.alloc(Stmt::Let(
            binding,
            expr,
            layout,
            arena.alloc(final_continuation),
        ))
    },
);
```

2023-07-11 08:11 UTC, JTeeuwissen commented on crates/compiler/mono/src/drop_specialization.rs
> +                ));
And perhaps update the name as well. If it's not really final.

2023-07-12 16:34 UTC, JTeeuwissen approved these changes

2023-07-12 17:04 UTC, merged