Re-organize the LLVM build instructions
roc-lang/roc pull request #6059
Opened 2023-11-21 23:39 UTC by stefanv

- `zig` needs `lib` directory
- `llvm` needs development headers
- Keep installation instructions together
- Group by platform
- No longer split installation and debugging instructions

2023-11-22 13:08 UTC, rtfeldman commented on BUILDING_FROM_SOURCE.md
> +- For systems with Snap, you can install with `snap install zig --classic --beta`
I think referencing Ubuntu by name here is probably helpful to people running Ubuntu.

How about this?

```suggestion
- For systems with Snap (such as Ubuntu), you can install with `snap install zig --classic --beta`
```

2023-11-22 13:22 UTC, rtfeldman commented on BUILDING_FROM_SOURCE.md
> +export LLVM_SYS_160_PREFIX=/usr/local/opt/llvm@16
Hm, shouldn't this also use `brew --prefix`? 🤔  e.g.

```suggestion
export LLVM_SYS_160_PREFIX=$(brew --prefix llvm@16)
```

2023-11-22 13:23 UTC, rtfeldman requested changes
Couple of suggestions/questions, but looking good so far! Thanks @stefanv! 😃

2023-11-22 22:21 UTC, stefanv commented
Thanks for the review @rtfeldman; I've updated the PR accordingly.

2023-11-23 02:46 UTC, rtfeldman approved these changes
Awesome, thanks so much @stefanv! 🎉

2023-11-23 02:46 UTC, merged