add: sort on function names in the docs
roc-lang/roc pull request #6526
Opened 2024-02-15 16:26 UTC by gunnarahlberg

The sorting of the entries is added, with styling that mimics neighbours.

Attributes are sorted by javasrcipts native comparison. Example:  Str concat and contains are after UTF8ByteProblem and UTF8Problem

This is related to the https://github.com/roc-lang/roc/issues/6494

I saw the list in the ticket. This PR ticks some of the boxes
![Screen Shot 2024-02-15 at 17 26 11](https://github.com/roc-lang/roc/assets/15113/e599fce8-5d0f-43b8-b9e4-3a4e0d1a5b48)

2024-02-16 10:59 UTC, Anton-4 requested changes
Thanks for you contribution @gunnarahlberg, I like where this is going!

I failed to specify this in the issue but I think the sort button should be placed above `Utf8ByteProblem` (and under `Str`). This would follow UX best principles to put controls close to where they affect change. Otherwise if you're looking at the list for `Inspect` you are very likely to miss the Sort button all the way at the top.

Can you also try to make the Sort button stand out from the other items in the list? It's functionality is very different compared to the other links/buttons so we should visually indicate that.

2024-02-16 17:13 UTC, gunnarahlberg commented
100% 

I was thinking something similar to what you said in your comment 
Will fix 

What about the cargo/rust stuff? It's literally my first time I do anything in Rust, all help is welcome. Should there be specific js files per feature?

2024-02-16 17:19 UTC, Anton-4 commented
> I was thinking something similar to what you said in your comment
Will fix

Awesome, thank you @gunnarahlberg :)

> What about the cargo/rust stuff? It's literally my first time I do anything in Rust, all help is welcome. 

That all looks good!

> Should there be specific js files per feature?

Good point! Having separate files probably leads to a slight additional delay per file. Feel free to combine both in script.js

2024-02-19 22:40 UTC, gunnarahlberg commented
@Anton-4 - I suggest that we instead of one sort button per section have just one sort button
Otherwise, this happens :)

![Screen Shot 2024-02-19 at 22 44 19](https://github.com/roc-lang/roc/assets/15113/cfc84cd1-d3ee-46f8-8a7e-2a28c9382177)

What do you think? Would it be ok with you if the sort button happens once and sorts all the sections?

Like this

![image](https://github.com/roc-lang/roc/assets/15113/1cb60c20-18db-47a7-8df6-1ec540833097)

2024-02-20 16:27 UTC, Anton-4 commented
> Otherwise, this happens :)

Hmm, is there no way to only show the sort button in the expanded view, after you've clicked on e.g. `Str`?

2024-02-20 22:49 UTC, gunnarahlberg commented
Oh, good idea, I didn't think about that before, let's try it out wouldn't be much trouble

2024-03-22 00:31 UTC, lukewilliamboswell commented
@gunnarahlberg do you intend to change the behaviour so that Sort is only displayed in the expanded view? We might need to detect when links under `class="sidebar-sub-entries"` are hidden to do this. 

Also, I think there are some formatting things for CI. 

Otherwise this is looking really useful. 👍

2024-03-22 11:47 UTC, gunnarahlberg commented
> @gunnarahlberg do you intend to change the behaviour so that Sort is only displayed in the expanded view? We might need to detect when links under `class="sidebar-sub-entries"` are hidden to do this.
> 
> Also, I think there are some formatting things for CI.
> 
> Otherwise this is looking really useful. 👍

Yes there is a change needed like that, I’ve been on vacation for a while

honestly I got it to work but not to be pretty 😥 e.g. it always looks wrong no matter how I place it

2024-03-22 21:38 UTC, gunnarahlberg commented
Ok i have this idea that might work

We show a sort button to the right of the section title when the section is expanded 

Some of the font awesome icons are used in this docs. Maybe this icon works, what do you think? [arrow down a-z](https://fontawesome.com/icons/arrow-down-a-z?f=classic&s=solid) the classic solid is free others are nicer but requires a license

2024-03-22 22:12 UTC, rtfeldman commented
Regarding icons and licenses, my preference is (and I know we aren't doing this consistently, but I'm working on changing the other place we use an icon):
* Only use SVGs that have a free license (attribution is fine; we can do that in a comment)
* Add the SVG source code to an existing .css file (e.g. [like this](https://stackoverflow.com/a/10768631)), so it doesn't require an extra network request (like a separate .svg file would) and also doesn't require the SVG's contents being inlined everywhere we use it.

2024-03-23 09:37 UTC, Anton-4 commented
> We show a sort button to the right of the section title when the section is expanded

Sounds good!

2025-02-14 22:24 UTC, closed without merging