Add `roc test --ignore-error` flag
roc-lang/roc pull request #6623
Opened 2024-04-02 21:39 UTC by horriblename

closes #6622 

adds new flag to allow tests to be run even if build errors occurred, like `roc run`

2024-04-05 09:58 UTC, Anton-4 requested changes
Looks good @horriblename, I just improved some names. Can you add a test that uses the ignore-build-errors flag?

2024-04-06 17:24 UTC, Anton-4 approved these changes
Thanks @horriblename!

2024-04-09 17:11 UTC, horriblename commented
@Anton-4 ci checks got blocked earlier as some commits are "partially signed", can you sign it again?

2024-04-09 17:16 UTC, Anton-4 commented
> @Anton-4 ci checks failed earlier as some commits are "partially verified", can you sign it again?

I believe there was also a failure in the wasm tests but I'll run CI again and we'll see what happens :smile:

2024-04-21 22:28 UTC, ayazhafiz commented on crates/cli/src/lib.rs
> +        exec_mode: exec_mode.clone(),
```suggestion
        exec_mode,
```

This should fix the issue in CI.

2024-04-22 11:56 UTC, Anton-4 commented on crates/cli/src/lib.rs
> +        exec_mode: exec_mode.clone(),
Thanks Ayaz :)

2025-02-14 22:24 UTC, closed without merging