Adding the decimal functions
roc-lang/roc pull request #7261
Opened 2024-11-28 16:09 UTC by wizard7377

Adding the builtins for `maxDec`, `minDec`, and `toDec`, and `toDecChecked` to the compiler, fixing #5446 and #5486 .

2024-12-19 01:09 UTC, lukewilliamboswell approved these changes

2024-12-20 08:43 UTC, smores56 commented
@wizard7377 can you [sign all of these commits](https://github.com/roc-lang/roc/blob/main/CONTRIBUTING.md#commit-signing)? It looks like the first one got missed. We can re-approve and merge once that's done.

2024-12-20 20:01 UTC, Anton-4 commented
Tomorrow I'm going to finish altering the panics check to actually show the locations of the new panics

2024-12-21 19:14 UTC, Anton-4 commented
This problem is harder than it seems, so I searched and found cargo-scout. I forked it and adapted it for our use case but it's reporting zero new clippy errors, I did  a bunch of debugging but was not yet able to figure it out, I will continue on Monday.

2024-12-23 19:08 UTC, Anton-4 requested changes

2024-12-23 19:08 UTC, Anton-4 commented on crates/compiler/gen_llvm/src/llvm/lowlevel.rs
> +                                .unwrap();
Can this unwrap be reasonably avoided so we don't crash the compiler with a bad error message?

2024-12-23 19:08 UTC, Anton-4 commented on crates/compiler/gen_llvm/src/llvm/lowlevel.rs
> +}
Can these unwraps be reasonably avoided so we don't crash the compiler with a bad error message?

2024-12-23 19:09 UTC, Anton-4 commented
I'm going to take two days off and I did not want to block this, so I reverted the panic check changes and shared the problematic unwraps above.

2024-12-23 19:10 UTC, Anton-4 commented
If the unwraps can not be avoided with reasonable effort, we should use `expect` with a nice error message.

2025-02-14 22:26 UTC, isaacvando commented
Going to close this PR given the Zig rewrite

2025-02-14 22:26 UTC, closed without merging