Fixed Issue #6929
roc-lang/roc pull request #7389
Opened 2024-12-18 22:56 UTC by timonkrebs

Fixed the Issue Escape unicode when inspecting a Str #6929

2024-12-20 13:44 UTC, Anton-4 commented
Thanks for your contribution @timonkrebs :)

We prefer to avoid bundling different changes in a single PR like this. Can you remove the .devcontainer folder for now and open a topic for its addition in the [zulip ideas channel](https://roc.zulipchat.com/#narrow/channel/304641-ideas)? We've got something similar going with nix and I'd like to make sure this is worth the added maintenance.

2024-12-20 23:18 UTC, timonkrebs commented
Thank you for your awsome work on roc.
I started a topic: https://roc.zulipchat.com/#narrow/channel/304641-ideas/topic/devcontainer

2024-12-23 13:46 UTC, Anton-4 requested changes

2024-12-23 13:46 UTC, Anton-4 commented on crates/compiler/builtins/roc/Inspect.roc
> +            escapeS = Str.replaceEach s "*" "*" # escape exotic characters like invisible unicode characters \u(feff)
This `replaceEach` does not seem to make any changes? It uses "*" twice

2024-12-23 19:54 UTC, closed without merging